function t121_setHeight(recid){var div=$("#youtubeiframe"+recid);var height=div.width()*0.5625;div.height(height);div.parent().height(height)}
function t142_checkSize(recid){var el=$("#rec"+recid).find(".t142__submit");if(el.length){var btnheight=el.height()+5;var textheight=el[0].scrollHeight;if(btnheight<textheight){var btntext=el.text();el.addClass("t142__submit-overflowed");el.html("<span class=\"t142__text\">"+btntext+"</span>")}}}
function t190_scrollToTop(){$('html, body').animate({scrollTop:0},700)}
function t364_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t-popup');popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show')},50);$('body').addClass('t-body_popupshowed');el.find('.t-popup').click(function(e){if(e.target==this){t364_closePopup()}});el.find('.t-popup__close').click(function(e){t364_closePopup()});el.find('.t364__text').click(function(){t364_closePopup();t364_createCookie('t364closefb','yes',30)});el.find('a[href*=#]').click(function(e){var url=$(this).attr('href');if(!url||url.substring(0,7)!='#price:'){t364_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){$('body').addClass('t-body_popupshowed')},300)}}});$(document).keydown(function(e){if(e.keyCode==27){t364_closePopup()}})}
function t364_closePopup(){$('body').removeClass('t-body_popupshowed');$('.t-popup').removeClass('t-popup_show');setTimeout(function(){$('.t-popup').not('.t-popup_show').css('display','none')},300)}
function t364_resizePopup(recid){var el=$("#rec"+recid),div=el.find(".t-popup__container").height(),win=$(window).height()-30,popup=el.find(".t-popup__container");if(div>win){popup.addClass('t-popup__container-static')}else{popup.removeClass('t-popup__container-static')}}
function t364_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}
function t364_createCookie(name,value,days){if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));var expires="; expires="+date.toGMTString()}
else{var expires=""}
document.cookie=name+"="+value+expires+"; path=/"}
function t364_readCookie(name){var nameEQ=name+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' '){c=c.substring(1,c.length)}
if(c.indexOf(nameEQ)==0){return c.substring(nameEQ.length,c.length)}}
return null}
function t364_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t-popup'),hook=el.attr('data-tooltip-hook'),analitics=el.attr('data-track-popup');var cookieexist=el.attr('data-cookies-exist');if(cookieexist!=='yes'){var cookie=t364_readCookie('')}else{var cookie=t364_readCookie('t364closefb')}
if(hook!==''&&cookie!=='yes'){var obj=$('a[href="'+hook+'"]');obj.click(function(e){t364_showPopup(recid);t364_resizePopup(recid);e.preventDefault();if(analitics>''){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}})}}
function t365_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t-popup');popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show')},50);$('body').addClass('t-body_popupshowed');el.find('.t-popup').click(function(e){if(e.target==this){t365_closePopup()}});el.find('.t-popup__close').click(function(e){t365_closePopup()});el.find('.t365__text').click(function(){t365_closePopup();t365_createCookie('t365closefb','yes',30)});el.find('a[href*=#]').click(function(e){var url=$(this).attr('href');if(!url||url.substring(0,7)!='#price:'){t365_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){$('body').addClass('t-body_popupshowed')},300)}}});$(document).keydown(function(e){if(e.keyCode==27){t365_closePopup()}})}
function t365_closePopup(){$('body').removeClass('t-body_popupshowed');$('.t-popup').removeClass('t-popup_show');setTimeout(function(){$('.t-popup').not('.t-popup_show').css('display','none')},300)}
function t365_resizePopup(recid){var el=$("#rec"+recid),div=el.find(".t-popup__container").height(),win=$(window).height()-30,popup=el.find(".t-popup__container");if(div>win){popup.addClass('t-popup__container-static')}else{popup.removeClass('t-popup__container-static')}}
function t365_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}
function t365_createCookie(name,value,days){if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));var expires="; expires="+date.toGMTString()}
else{var expires=""}
document.cookie=name+"="+value+expires+"; path=/"}
function t365_readCookie(name){var nameEQ=name+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' '){c=c.substring(1,c.length)}
if(c.indexOf(nameEQ)==0){return c.substring(nameEQ.length,c.length)}}
return null}
function t365_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t-popup'),hook=el.attr('data-tooltip-hook'),analitics=el.attr('data-track-popup');var cookieexist=el.attr('data-cookies-exist');if(cookieexist!=='yes'){var cookie=t365_readCookie('')}else{var cookie=t365_readCookie('t365closefb')}
if(hook!==''&&cookie!=='yes'){var obj=$('a[href="'+hook+'"]');obj.click(function(e){t365_showPopup(recid);t365_resizePopup(recid);e.preventDefault();if(analitics>''){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}})}}
function t367_createCookie(name,value,days){if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));var expires="; expires="+date.toGMTString()}
else var expires="";document.cookie=name+"="+value+expires+"; path=/"}
function t367_readCookie(name){var nameEQ=name+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1,c.length);if(c.indexOf(nameEQ)==0)return c.substring(nameEQ.length,c.length)}
return null}
function t367_autoInit(recid){var el=$('#rec'+recid).find('.t367__opener');var name=el.attr('data-cookie-name');var time=el.attr('data-cookie-time');var value="t367cookie";var cookie=t367_readCookie(name);var delay=el.attr('data-trigger-time');var delaytime=delay*1000;if(cookie){$("#rec"+recid+" .t367").html("")}else if(el.length){setTimeout(function(){el.trigger('click');$("#rec"+recid+" .t367").html("");t367_createCookie(name,value,time)},delaytime)}}
function t390_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t-popup');popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show')},50);$('body').addClass('t-body_popupshowed');el.find('.t-popup').click(function(e){if(e.target==this){t390_closePopup()}});el.find('.t-popup__close').click(function(e){t390_closePopup()});el.find('a[href*=#]').click(function(e){var url=$(this).attr('href');if(!url||url.substring(0,7)!='#price:'){t390_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){$('body').addClass('t-body_popupshowed')},300)}}});$(document).keydown(function(e){if(e.keyCode==27){t390_closePopup()}})}
function t390_closePopup(){$('body').removeClass('t-body_popupshowed');$('.t-popup').removeClass('t-popup_show');setTimeout(function(){$('.t-popup').not('.t-popup_show').css('display','none')},300)}
function t390_resizePopup(recid){var el=$("#rec"+recid),div=el.find(".t-popup__container").height(),win=$(window).height()-120,popup=el.find(".t-popup__container");if(div>win){popup.addClass('t-popup__container-static')}else{popup.removeClass('t-popup__container-static')}}
function t390_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t390_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t-popup'),hook=el.attr('data-tooltip-hook'),analitics=el.attr('data-track-popup');if(hook!==''){var obj=$('a[href="'+hook+'"]');obj.click(function(e){t390_showPopup(recid);t390_resizePopup(recid);e.preventDefault();if(window.lazy=='y'){t_lazyload_update()}
if(analitics>''){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}})}}
function t398_init(recid){t398_addArrow(recid);t398_highlight();$('#rec'+recid).find(".t398").each(function(){var $hook=$(this).attr('data-tooltip-hook');var $margin=$(this).attr('data-tooltip-margin');if($hook!==''){var $obj=$('a[href="'+$hook+'"]');var $content=$(this).find('.t398__content').html();if($hook.charAt(0)=='#'){var touchDevices=!0}else{var touchDevices=!1}
var position=$(this).attr('data-tooltip-position');if(position!==''){}else{position='top'}
$obj.click(function(e){e.preventDefault()});$obj.tooltipster({'theme':'t398__tooltipster-noir t398__tooltipster-noir_'+recid+'','contentAsHTML':!0,'content':$content,interactive:!0,touchDevices:touchDevices,position:position,functionReady:function(origin,tooltip){$(".t398__tooltipster-noir_"+recid+"").css("margin-top",$margin)}})}})}
function t398_addArrow(recid){$('#rec'+recid).find(".t398").each(function(){var $hook=$(this).attr('data-tooltip-hook');var $obj=$('a[href="'+$hook+'"]');var arrow=$(this).attr('data-add-arrow');var arrow_height=$obj.height();if($hook!==''&&arrow!==''){$obj.append("<div class=\"t398__arrow t398__arrow_"+recid+"\" style=\"height: "+arrow_height+"\px;\"></div>")}})}
function t398_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t398__list_item a[href='"+url+"']").addClass("t-active");$(".t398__list_item a[href='"+url+"/']").addClass("t-active");$(".t398__list_item a[href='"+pathname+"']").addClass("t-active");$(".t398__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t398__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t398__list_item a[href='http://tilda.ws/%22+pathname+%22/']").addClass("t-active")}
t431_createTable=function(recid,tablehead,tabledata,tablecolsize,hastargetblank,btnstyles,t431__tdstyles,t431__thstyles,t431__oddrowstyles,t431__evenrowstyles){var t431__arrayColSize=t431_parseData(tablecolsize);var t431__arrayHead=t431_parseData(tablehead);var t431__arrayData=t431_parseData(tabledata);var t431__maxcolnumber=t431__findMaxRowLengthInTable(t431__arrayHead,t431__arrayData);var t431__colWidth=t431__setColumnsWidth(t431__arrayColSize,t431__maxcolnumber,recid);if(t431__colWidth[0].myText&&t431__colWidth[0].myText[t431__colWidth[0].myText.length-1]=="%"){for(var i=0;i<t431__colWidth.length;i++){t431__colWidth[i].myText=t431__colWidth[i].myText.slice(0,-1);t431__colWidth[i].myText+="vw"}}
var t431__container=$('#rec'+recid+' .t431 .t-container .t431__table');var t431__htmlTable="";if(t431__arrayHead){t431__htmlTable+=t431__generateHtml(recid,t431__arrayHead,"th",hastargetblank,t431__colWidth,btnstyles,t431__thstyles,null,null,t431__maxcolnumber)}
t431__container.append(t431__htmlTable);t431__htmlTable="";if(t431__arrayData){t431__htmlTable+=t431__generateHtml(recid,t431__arrayData,"td",hastargetblank,t431__colWidth,btnstyles,t431__tdstyles,t431__oddrowstyles,t431__evenrowstyles,t431__maxcolnumber)}
t431__container.append(t431__htmlTable)};t431_setHeadWidth=function(recid){if($(window).width()>960){var t431__tbody=$('#rec'+recid+' .t431 .t431__tbody');var t431__thead=$('#rec'+recid+' .t431 .t431__thead');t431__tbody.css("display","block");t431__thead.css("display","block");var t431__colWidth=$('#rec'+recid+' .t431 .t431__tbody tr:first').children().map(function(){return $(this).width()});if($('#rec'+recid+' .t431 .t431__tbody tr td:first').css('border-left-width').length>=3){var t431__verticalborder=$('#rec'+recid+' .t431 .t431__tbody tr td:first').css('border-left-width').slice(0,-2)}
$('#rec'+recid+' .t431 .t431__thead tr').children().each(function(i,v){if($(v).is(":last-child")){$(v).width(t431__colWidth[i]+(t431__tbody.width()-$('#rec'+recid+' .t431 .t431__tbody tr:first').width()))}else{$(v).width(t431__colWidth[i]+(+t431__verticalborder))}})}};t431__findMaxRowLengthInTable=function(arrayhead,arraydata){var t431__headmaxlength=0;var t431__datamaxlength=0;if(arrayhead){t431__headmaxlength=t431__findMaxRowLengInArray(arrayhead)}
if(arraydata){t431__datamaxlength=t431__findMaxRowLengInArray(arraydata)}
if(t431__datamaxlength>t431__headmaxlength){return t431__datamaxlength}else{return t431__headmaxlength}};t431__findMaxRowLengInArray=function(curarray){var t431__maxlength=0;for(var i=0;i<curarray.length;i++){if(curarray[i].length>t431__maxlength){t431__maxlength=curarray[i].length}}
return t431__maxlength};t431__setColumnsWidth=function(t431__colwidth,t431__colsnumber,recid){if(t431__colwidth){return t431__colwidth[0]}else{var t431__tablewidth=$('#rec'+recid+' .t431 .t-container .t-col').width();return(t431__tablewidth/t431__colsnumber+"px")}};t431__generateHtml=function(recid,arrayValues,coltag,hastargetblank,colWidth,btnstyles,colstyles,oddrowstyles,evenrowstyles,maxcolnumber){var t431__htmlpart="";if(coltag=="td"){var t431__theadorbodytag="tbody"}else{var t431__theadorbodytag="thead"}
t431__htmlpart+="<"+t431__theadorbodytag+" class=\"t431__"+t431__theadorbodytag+"\">";if($('#rec'+recid+' .t431 .t-container .t431__thead th').length>0&&$('#rec'+recid+' .t431 .t-container .t431__thead th').css("border-bottom-width")[0]!="0"){var t431__firstbodyrowstyle="border-top: 0 !important;"}
for(var i=0;i<arrayValues.length;i++){if(coltag=="td"){if((i+1)%2>0){t431__htmlpart+="<tr class=\"t431__oddrow\""+"style=\""+oddrowstyles+"\">"}else{t431__htmlpart+="<tr class=\"t431__evenrow\""+"style=\""+evenrowstyles+"\">"}}else{t431__htmlpart+="<tr>"}
var t431__addingcols=0;if(arrayValues[i].length<maxcolnumber){t431__addingcols=maxcolnumber-arrayValues[i].length}
for(var j=0;j<(arrayValues[i].length+t431__addingcols);j++){if(arrayValues[i][j]){if(Array.isArray(colWidth)&&colWidth[j]){var t431__curWidth=colWidth[j].myText}else{var t431__curWidth=colWidth}
if(i==0&&coltag=="td"){var t431__colwithattr="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+t431__firstbodyrowstyle+"\">"}else{var t431__colwithattr="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+"\">"}
if(arrayValues[i][j].myHref){var t431__tblank="";if(hastargetblank){var t431__tblank="target=\"_blank\""}
if(arrayValues[i][j].myHrefType=="link"){var t431__linkwithattr="<a href=\""+arrayValues[i][j].myHref+"\""+t431__tblank+">";var t431__linkclosetag="</a>"}else{var t431__linkwithattr="<div class=\"t431__btnwrapper\"><a href=\""+arrayValues[i][j].myHref+"\""+t431__tblank+" class=\"t-btn t-btn_sm\" style=\""+btnstyles+"\"><table style=\"width:100%; height:100%;\"><tr><td>";var t431__linkclosetag="</td></tr></table></a></div>"}
t431__htmlpart+=t431__colwithattr+t431__linkwithattr+arrayValues[i][j].myText+t431__linkclosetag+"</"+coltag+">"}else{t431__htmlpart+=t431__colwithattr+arrayValues[i][j].myText+"</"+coltag+">"}}else{t431__htmlpart+="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+"\">"+"</"+coltag+">"}}
t431__htmlpart+="</tr>"}
t431__htmlpart+="</"+t431__theadorbodytag+">";return t431__htmlpart};t431_parseData=function(t431__data){if(t431__data!=""&&typeof t431__data!='undefined')
{t431__data=t431__addBrTag(t431__data);var t431__arrayTable=new Array();var t431__arrayRow=new Array();var t431__curItem={myText:"",myHref:"",myHrefType:""};var t431__HasLink="";var t431__HasLinkWithSpace="";var t431__HasBtn="";var t431__HasBtnWithSpace="";var t431__EndOfLine="";for(var i=0;i<t431__data.length;i++)
{if(t431__data[i]==";"&&!((t431__data[i-1]&&(t431__data[i-1]=="t"))&&(t431__data[i-2]&&(t431__data[i-2]=="g"||t431__data[i-2]=="l"))&&(t431__data[i-3]&&(t431__data[i-3]=="&")))&&!((t431__data[i-1]&&(t431__data[i-1]=="p"))&&(t431__data[i-2]&&(t431__data[i-2]=="m"))&&(t431__data[i-3]&&(t431__data[i-3]=="a"))&&(t431__data[i-4]&&(t431__data[i-4]=="&")))){t431__arrayRow.push(t431__curItem);var t431__curItem={myText:"",myHref:""};t431__HasLink="";t431__HasLinkWithSpace="";t431__HasBtn="";t431__HasBtnWithSpace=""}else{if(t431__HasLink=="link="||t431__HasLinkWithSpace==" link="||t431__HasBtn=="button="||t431__HasBtnWithSpace==" button="){if(t431__curItem.myHref==""&&t431__HasLink=="link="){t431__curItem.myText=t431__curItem.myText.slice(0,-5);t431__curItem.myHrefType="link"}else{if(t431__curItem.myHref==""&&t431__HasLinkWithSpace==" link="){t431__curItem.myText=t431__curItem.myText.slice(0,-6);t431__curItem.myHrefType="link"}else{if(t431__curItem.myHref==""&&t431__HasBtn=="button="){t431__curItem.myText=t431__curItem.myText.slice(0,-7);t431__curItem.myHrefType="btn"}else{if(t431__curItem.myHref==""&&t431__HasBtnWithSpace==" button="){t431__curItem.myText=t431__curItem.myText.slice(0,-8);t431__curItem.myHrefType="btn"}}}}
t431__curItem.myHref+=(t431__data[i])}else{t431__curItem.myText+=(t431__data[i]);t431__HasLink=t431__checkSubstr("link=",t431__HasLink,t431__data[i]);t431__HasLinkWithSpace=t431__checkSubstr(" link=",t431__HasLinkWithSpace,t431__data[i]);t431__HasBtn=t431__checkSubstr("button=",t431__HasBtn,t431__data[i]);t431__HasBtnWithSpace=t431__checkSubstr(" button=",t431__HasBtnWithSpace,t431__data[i])}
t431__EndOfLine=t431__checkSubstr("<br />",t431__EndOfLine,t431__data[i]);if(t431__EndOfLine=="<br />"){if(t431__curItem.myHref){t431__curItem.myHref=t431__curItem.myHref.slice(0,-6)}else{t431__curItem.myText=t431__curItem.myText.slice(0,-6)}
t431__arrayRow.push(t431__curItem);t431__arrayTable.push(t431__arrayRow);var t431__curItem={myText:"",myHref:""};t431__HasLink="";t431__HasLinkWithSpace="";t431__HasBtn="";t431__HasBtnWithSpace="";t431__arrayRow=new Array()}}}
if(t431__arrayRow.length>0||t431__curItem.myText!=""){if(t431__curItem!=""){t431__arrayRow.push(t431__curItem)}
t431__arrayTable.push(t431__arrayRow)}}
return t431__arrayTable};t431__checkSubstr=function(t431__targetSubstr,t431__curSubstr,t431__curSymbol){if(!t431__curSubstr&&t431__curSymbol==t431__targetSubstr[0]){return t431__curSymbol}else{if(t431__curSubstr){for(var i=0;i<(t431__targetSubstr.length-1);i++){if(t431__curSubstr[t431__curSubstr.length-1]==t431__targetSubstr[i]&&t431__curSymbol==t431__targetSubstr[i+1]){return(t431__curSubstr+=t431__curSymbol)}}}}};t431__addBrTag=function(t431__oldStringItem){if(typeof t431__oldStringItem=='undefined')return;var t431__newStringItem="";for(var i=0;i<t431__oldStringItem.length;i++){if(t431__oldStringItem[i]=="\n"||t431__oldStringItem[i]=="\r"){t431__newStringItem+="<br />"}else{t431__newStringItem+=t431__oldStringItem[i]}}
return t431__newStringItem};function t453_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t453__item a[href='"+url+"']").addClass("t-active");$(".t453__item a[href='"+url+"/']").addClass("t-active");$(".t453__item a[href='"+pathname+"']").addClass("t-active");$(".t453__item a[href='/"+pathname+"']").addClass("t-active");$(".t453__item a[href='"+pathname+"/']").addClass("t-active");$(".t453__item a[href='http://tilda.ws/%22+pathname+%22/']").addClass("t-active")}
function t453_checkAnchorLinks(recid){if($(window).width()>=960){var t453_navLinks=$("#rec"+recid+" .t453__item a:not(.tooltipstered)[href*='#']");if(t453_navLinks.length>0){t453_catchScroll(t453_navLinks)}}}
function t453_catchScroll(t453_navLinks){var t453_clickedSectionId=null,t453_sections=new Array(),t453_sectionIdTonavigationLink={},t453_interval=100,t453_lastCall,t453_timeoutId,t453_offsetTop=$(".t453").attr("data-offset-top");if(typeof t453_offsetTop=="undefined"){t453_offsetTop=0}
t453_navLinks.each(function(){var t453_cursection=t453_getSectionByHref($(this));if(typeof t453_cursection.attr("id")!="undefined"){t453_sections.push(t453_cursection)}
t453_sectionIdTonavigationLink[t453_cursection.attr("id")]=$(this)});t453_highlightNavLinks(t453_navLinks,t453_sections,t453_sectionIdTonavigationLink,t453_clickedSectionId,t453_offsetTop);t453_navLinks.click(function(){if(!$(this).hasClass("tooltipstered")){t453_navLinks.removeClass('t-active');t453_sectionIdTonavigationLink[t453_getSectionByHref($(this)).attr("id")].addClass('t-active');t453_clickedSectionId=t453_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t453_now=new Date().getTime();if(t453_lastCall&&t453_now<(t453_lastCall+t453_interval)){clearTimeout(t453_timeoutId);t453_timeoutId=setTimeout(function(){t453_lastCall=t453_now;t453_clickedSectionId=t453_highlightNavLinks(t453_navLinks,t453_sections,t453_sectionIdTonavigationLink,t453_clickedSectionId,t453_offsetTop)},t453_interval-(t453_now-t453_lastCall))}else{t453_lastCall=t453_now;t453_clickedSectionId=t453_highlightNavLinks(t453_navLinks,t453_sections,t453_sectionIdTonavigationLink,t453_clickedSectionId,t453_offsetTop)}})}
function t453_getSectionByHref(curlink){if(curlink.is('[href*="#rec"]')){return $(".r[id='"+curlink.attr("href").substring(1)+"']")}
else{return $(".r[data-record-type='215']").has("a[name='"+curlink.attr("href").substring(1)+"']")}}
function t453_highlightNavLinks(t453_navLinks,t453_sections,t453_sectionIdTonavigationLink,t453_clickedSectionId,offsetTop){var t453_scrollPosition=$(window).scrollTop(),t453_valueToReturn=t453_clickedSectionId;$(t453_sections).each(function(e){var t453_curSection=$(this),t453_sectionTop=t453_curSection.offset().top,t453_id=t453_curSection.attr('id'),t453_navLink=t453_sectionIdTonavigationLink[t453_id];if(t453_scrollPosition>=(t453_sectionTop-offsetTop)||(t453_sections[0].attr("id")==t453_id&&$(window).scrollTop()>=$(document).height()-$(window).height())){if(t453_clickedSectionId==null&&!t453_navLink.hasClass('t-active')){t453_navLinks.removeClass('t-active');t453_navLink.addClass('t-active');t453_valueToReturn=null}else{if(t453_clickedSectionId!=null&&t453_id==t453_clickedSectionId){t453_valueToReturn=null}}
return!1}});return t453_valueToReturn}
function t453_appearMenu(recid){var window_width=$(window).width();var record=$("#rec"+recid);record.find(".t453").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");console.log(appearoffset)
if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.hasClass('t453__beforeready')){el.removeClass('t453__beforeready')}}else{el.addClass('t453__beforeready')}}})}
function t456_setListMagin(recid,imglogo){if($(window).width()>980){var t456__menu=$('#rec'+recid+' .t456');var t456__leftpart=t456__menu.find('.t456__leftwrapper');var t456__listpart=t456__menu.find('.t456__list');if(imglogo){t456__listpart.css("margin-right",t456__leftpart.width())}else{t456__listpart.css("margin-right",t456__leftpart.width()+30)}}}
function t456_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t456__list_item a[href='"+url+"']").addClass("t-active");$(".t456__list_item a[href='"+url+"/']").addClass("t-active");$(".t456__list_item a[href='"+pathname+"']").addClass("t-active");$(".t456__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t456__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t456__list_item a[href='http://tilda.ws/%22+pathname+%22/']").addClass("t-active")}
function t456_checkAnchorLinks(recid){if($(window).width()>=960){var t456_navLinks=$("#rec"+recid+" .t456__list_item a:not(.tooltipstered)[href*='#']");if(t456_navLinks.length>0){t456_catchScroll(t456_navLinks)}}}
function t456_catchScroll(t456_navLinks){var t456_clickedSectionId=null,t456_sections=new Array(),t456_sectionIdTonavigationLink=[],t456_interval=100,t456_lastCall,t456_timeoutId;t456_navLinks=$(t456_navLinks.get().reverse());t456_navLinks.each(function(){var t456_cursection=t456_getSectionByHref($(this));if(typeof t456_cursection.attr("id")!="undefined"){t456_sections.push(t456_cursection)}
t456_sectionIdTonavigationLink[t456_cursection.attr("id")]=$(this)});$(window).bind('resize',t_throttle(function(){t456_updateSectionsOffsets(t456_sections)},200));$('.t456').bind('displayChanged',function(){t456_updateSectionsOffsets(t456_sections)});setInterval(function(){t456_updateSectionsOffsets(t456_sections)},5000);setTimeout(function(){t456_updateSectionsOffsets(t456_sections);t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId)},1000);t456_navLinks.click(function(){if(!$(this).hasClass("tooltipstered")){t456_navLinks.removeClass('t-active');t456_sectionIdTonavigationLink[t456_getSectionByHref($(this)).attr("id")].addClass('t-active');t456_clickedSectionId=t456_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t456_now=new Date().getTime();if(t456_lastCall&&t456_now<(t456_lastCall+t456_interval)){clearTimeout(t456_timeoutId);t456_timeoutId=setTimeout(function(){t456_lastCall=t456_now;t456_clickedSectionId=t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId)},t456_interval-(t456_now-t456_lastCall))}else{t456_lastCall=t456_now;t456_clickedSectionId=t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId)}})}
function t456_updateSectionsOffsets(sections){$(sections).each(function(){var t456_curSection=$(this);t456_curSection.attr("data-offset-top",t456_curSection.offset().top)})}
function t456_getSectionByHref(curlink){var t456_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t456_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t456_curLinkValue.substring(1)+"']")}}
function t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId){var t456_scrollPosition=$(window).scrollTop(),t456_valueToReturn=t456_clickedSectionId;if(t456_sections.length!=0&&t456_clickedSectionId==null&&t456_sections[t456_sections.length-1].attr("data-offset-top")>(t456_scrollPosition+300)){t456_navLinks.removeClass('t-active');return null}
$(t456_sections).each(function(e){var t456_curSection=$(this),t456_sectionTop=t456_curSection.attr("data-offset-top"),t456_id=t456_curSection.attr('id'),t456_navLink=t456_sectionIdTonavigationLink[t456_id];if(((t456_scrollPosition+300)>=t456_sectionTop)||(t456_sections[0].attr("id")==t456_id&&t456_scrollPosition>=$(document).height()-$(window).height())){if(t456_clickedSectionId==null&&!t456_navLink.hasClass('t-active')){t456_navLinks.removeClass('t-active');t456_navLink.addClass('t-active');t456_valueToReturn=null}else{if(t456_clickedSectionId!=null&&t456_id==t456_clickedSectionId){t456_valueToReturn=null}}
return!1}});return t456_valueToReturn}
function t456_setPath(){}
function t456_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t456").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t456").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t456_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t456").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t456_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t456").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t456_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t456"),burger=el.find(".t456__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t456_opened")});$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t509_setHeight(recid){var t509__el=$("#rec"+recid);var t509__image=t509__el.find(".t509__blockimg");t509__image.each(function(){var t509__width=$(this).attr("data-image-width");var t509__height=$(this).attr("data-image-height");var t509__ratio=t509__height/t509__width;var t509__padding=t509__ratio*100;$(this).css("padding-bottom",t509__padding+"%")});if($(window).width()>960){var t509__textwr=t509__el.find(".t509__textwrapper");var t509__deskimg=t509__el.find(".t509__desktopimg");t509__textwr.each(function(){$(this).css("height",t509__deskimg.innerHeight())})}}
function t533_equalHeight(recid){var el=$('#rec'+recid);el.find('.t533').css('visibility','visible');el.find('.t533__textwrapper').css('height','auto');$('#rec'+recid+' .t533__row').each(function(){var highestBox=0;$('.t533__textwrapper',this).each(function(){if($(this).height()>highestBox)highestBox=$(this).height()});if($(window).width()>=960&&$(this).is(':visible')){$('.t533__textwrapper',this).css('height',highestBox)}else{$('.t533__textwrapper',this).css('height',"auto")}})};function t537_setHeight(recid){var t537__el=$("#rec"+recid),t537__image=t537__el.find(".t537__bgimg:first"),t537__width=t537__image.attr("data-image-width"),t537__height=t537__image.attr("data-image-height"),t537__ratio=t537__height/t537__width,t537__padding=t537__ratio*100;$("#rec"+recid+" .t537__bgimg").css("padding-bottom",t537__padding+"%")}
function t544_setHeight(recid){var el=$('#rec'+recid);var sizer=el.find('.t544__sizer');var height=sizer.height();var width=sizer.width();var ratio=width/height;var imgwrapper=el.find(".t544__blockimg, .t544__textwrapper");var imgwidth=imgwrapper.width();if(height!=$(window).height()){imgwrapper.css({'height':((imgwidth/ratio)+'px')})}}
function t570_init(recid){if($(window).width()>750){t570_setMapHeight(recid);$(window).load(function(){t570_setMapHeight(recid)});$(window).resize(function(){t570_setMapHeight(recid)})}}
function t570_setMapHeight(recid){var t570__el=$('#rec'+recid),t570__map=t570__el.find('.t-map');var t570__textwrapper=t570__el.find('.t570__col_text').height();t570__map.css('height',t570__textwrapper).trigger('sizechange')}
function t592_init(recid){var element=$('#rec'+recid).find('.t592__descr');var highestBox=0;element.css('height','');element.each(function(){if($(this).height()>highestBox)highestBox=$(this).height()});if($(window).width()>=960){element.css('height',highestBox)}else{element.css('height','')}};function t616_init(recid){var el=$('#rec'+recid);if(el.find('.t616__title').length){t616_equalHeight(el.find('.t616__title'))}
if(el.find('.t616__text').length){t616_equalHeight(el.find('.t616__text'))}
if(el.find('.t616__price').length){t616_equalHeight(el.find('.t616__price'))}
t616_equalHeight(el.find('.t616__header'))};function t616_equalHeight(element){var highestBox=0;element.css('height','');element.each(function(){if($(this).height()>highestBox)highestBox=$(this).height()});if($(window).width()>=960){element.css('height',highestBox)}else{element.css('height','')}}
function t670_init(recid){t670_imageHeight(recid);t670_show(recid);t670_hide(recid)}
function t670_show(recid){var el=$("#rec"+recid),play=el.find('.t670__play');play.click(function(){if($(this).attr('data-slider-video-type')=='youtube'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://www.youtube.com/embed/"+url+"?autoplay=1\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>")}
if($(this).attr('data-slider-video-type')=='vimeo'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://player.vimeo.com/video/"+url+"?autoplay=1\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>")}
$(this).next().css('z-index','3')})}
function t670_hide(recid){var el=$("#rec"+recid),body=el.find('.t670__frame');el.on('updateSlider',function(){body.html('').css('z-index','')})}
function t670_imageHeight(recid){var el=$("#rec"+recid);var image=el.find(".t670__separator");image.each(function(){var width=$(this).attr("data-slider-image-width");var height=$(this).attr("data-slider-image-height");var ratio=height/width;var padding=ratio*100;$(this).css("padding-bottom",padding+"%")})}
function t678_onSuccess(t678_form){var t678_inputsWrapper=t678_form.find('.t-form__inputsbox');var t678_inputsHeight=t678_inputsWrapper.height();var t678_inputsOffset=t678_inputsWrapper.offset().top;var t678_inputsBottom=t678_inputsHeight+t678_inputsOffset;var t678_targetOffset=t678_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t678_target=t678_targetOffset-200}else{var t678_target=t678_targetOffset-100}
if(t678_targetOffset>$(window).scrollTop()||($(document).height()-t678_inputsBottom)<($(window).height()-100)){t678_inputsWrapper.addClass('t678__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t678_target},400);setTimeout(function(){t678_inputsWrapper.addClass('t678__inputsbox_hidden')},400)}
var successurl=t678_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t698_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t698_onSuccess(t698_form){var t698_inputsWrapper=t698_form.find('.t-form__inputsbox');var t698_inputsHeight=t698_inputsWrapper.height();var t698_inputsOffset=t698_inputsWrapper.offset().top;var t698_inputsBottom=t698_inputsHeight+t698_inputsOffset;var t698_targetOffset=t698_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t698_target=t698_targetOffset-200}else{var t698_target=t698_targetOffset-100}
if(t698_targetOffset>$(window).scrollTop()||($(document).height()-t698_inputsBottom)<($(window).height()-100)){t698_inputsWrapper.addClass('t698__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t698_target},400);setTimeout(function(){t698_inputsWrapper.addClass('t698__inputsbox_hidden')},400)}
var successurl=t698_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t700_init(recid,height){t700__setHeight(recid,height);var t700__doResize;$(window).resize(function(){clearTimeout(t700__doResize);t700__doResize=setTimeout(function(){t700__setHeight(recid)},200)})}
function t700__setHeight(recid,height){if(height==""||typeof height=="undefined"){var t700__el=$("#rec"+recid),t700__div=t700__el.find("#youtubeiframe"+recid),t700__height=t700__div.width()*0.5625;t700__div.height(t700__height);t700__div.parent().height(t700__height)}}
function t700_onSuccess(t700_form){var t700_inputsWrapper=t700_form.find('.t-form__inputsbox');var t700_inputsHeight=t700_inputsWrapper.height();var t700_inputsOffset=t700_inputsWrapper.offset().top;var t700_inputsBottom=t700_inputsHeight+t700_inputsOffset;var t700_targetOffset=t700_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t700_target=t700_targetOffset-200}else{var t700_target=t700_targetOffset-100}
if(t700_targetOffset>$(window).scrollTop()||($(document).height()-t700_inputsBottom)<($(window).height()-100)){t700_inputsWrapper.addClass('t700__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t700_target},400);setTimeout(function(){t700_inputsWrapper.addClass('t700__inputsbox_hidden')},400)}
var successurl=t700_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t702_onSuccess(t702_form){var t702_inputsWrapper=t702_form.find('.t-form__inputsbox');var t702_inputsHeight=t702_inputsWrapper.height();var t702_inputsOffset=t702_inputsWrapper.offset().top;var t702_inputsBottom=t702_inputsHeight+t702_inputsOffset;var t702_targetOffset=t702_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t702_target=t702_targetOffset-200}else{var t702_target=t702_targetOffset-100}
if(t702_targetOffset>$(window).scrollTop()||($(document).height()-t702_inputsBottom)<($(window).height()-100)){t702_inputsWrapper.addClass('t702__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t702_target},400);setTimeout(function(){t702_inputsWrapper.addClass('t702__inputsbox_hidden')},400)}
var successurl=t702_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t702_lockScroll(){var body=$("body");if(!body.hasClass('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||document.body.parentNode||document.body).scrollTop;body.addClass('t-body_scroll-locked');body.css("top","-"+bodyScrollTop+"px");body.attr("data-popup-scrolltop",bodyScrollTop)}}
function t702_unlockScroll(){var body=$("body");if(body.hasClass('t-body_scroll-locked')){var bodyScrollTop=$("body").attr("data-popup-scrolltop");body.removeClass('t-body_scroll-locked');body.css("top","");body.removeAttr("data-popup-scrolltop")
window.scrollTo(0,bodyScrollTop)}}
function t702_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t-popup');popup.css('display','block');el.find('.t-range').trigger('popupOpened');if(window.lazy=='y'){t_lazyload_update()}
setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show')},50);$('body').addClass('t-body_popupshowed t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){setTimeout(function(){t702_lockScroll()},500)}
el.find('.t-popup').click(function(e){if(e.target==this){t702_closePopup()}});el.find('.t-popup__close').click(function(e){t702_closePopup()});el.find('a[href*=#]').click(function(e){var url=$(this).attr('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){$('body').addClass('t-body_popupshowed')},300)}}});$(document).keydown(function(e){if(e.keyCode==27){t702_closePopup()}})}
function t702_closePopup(){$('body').removeClass('t-body_popupshowed t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){t702_unlockScroll()}
$('.t-popup').removeClass('t-popup_show');setTimeout(function(){$('.t-popup').not('.t-popup_show').css('display','none')},300)}
function t702_resizePopup(recid){var el=$("#rec"+recid),div=el.find(".t-popup__container").height(),win=$(window).height()-120,popup=el.find(".t-popup__container");if(div>win){popup.addClass('t-popup__container-static')}else{popup.removeClass('t-popup__container-static')}}
function t702_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t702_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t-popup'),hook=el.attr('data-tooltip-hook'),analitics=el.attr('data-track-popup');if(hook!==''){var obj=$('a[href="'+hook+'"]');obj.click(function(e){t702_showPopup(recid);t702_resizePopup(recid);e.preventDefault();if(window.lazy=='y'){t_lazyload_update()}
if(analitics>''){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}})}}
function t704_onSuccess(t704_form){var t704_inputsWrapper=t704_form.find('.t-form__inputsbox');var t704_inputsHeight=t704_inputsWrapper.height();var t704_inputsOffset=t704_inputsWrapper.offset().top;var t704_inputsBottom=t704_inputsHeight+t704_inputsOffset;var t704_targetOffset=t704_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t704_target=t704_targetOffset-200}else{var t704_target=t704_targetOffset-100}
if(t704_targetOffset>$(window).scrollTop()||($(document).height()-t704_inputsBottom)<($(window).height()-100)){t704_inputsWrapper.addClass('t704__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t704_target},400);setTimeout(function(){t704_inputsWrapper.addClass('t704__inputsbox_hidden')},400)}
var successurl=t704_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t706_onSuccessCallback(t706_form){if(typeof localStorage==='object'){try{localStorage.removeItem("tcart")}catch(e){console.log('Your web browser does not support localStorage.')}}
delete window.tcart;tcart__loadLocalObj();$(".t706__cartwin-products").slideUp(10,function(){});$(".t706__cartwin-bottom").slideUp(10,function(){});$(".t706 .t-form__inputsbox").slideUp(700,function(){});window.tcart_success='yes';try{tcart__unlockScroll()}catch(e){}}
function t712_onSuccess(t712_form){var t712_inputsWrapper=t712_form.find('.t-form__inputsbox');var t712_inputsHeight=t712_inputsWrapper.height();var t712_inputsOffset=t712_inputsWrapper.offset().top;var t712_inputsBottom=t712_inputsHeight+t712_inputsOffset;var t712_targetOffset=t712_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t712_target=t712_targetOffset-200}else{var t712_target=t712_targetOffset-100}
if(t712_targetOffset>$(window).scrollTop()||($(document).height()-t712_inputsBottom)<($(window).height()-100)){t712_inputsWrapper.addClass('t712__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t712_target},400);setTimeout(function(){t712_inputsWrapper.addClass('t712__inputsbox_hidden')},400)}
var successurl=t712_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t712_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t720_onSuccess(t720_form){var t720_inputsWrapper=t720_form.find('.t-form__inputsbox');var t720_inputsHeight=t720_inputsWrapper.height();var t720_inputsOffset=t720_inputsWrapper.offset().top;var t720_inputsBottom=t720_inputsHeight+t720_inputsOffset;var t720_targetOffset=t720_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t720_target=t720_targetOffset-200}else{var t720_target=t720_targetOffset-100}
if(t720_targetOffset>$(window).scrollTop()||($(document).height()-t720_inputsBottom)<($(window).height()-100)){t720_inputsWrapper.addClass('t720__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t720_target},400);setTimeout(function(){t720_inputsWrapper.addClass('t720__inputsbox_hidden')},400)}
var successurl=t720_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t720_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t724_init(recid){try{localStorage.setItem('localStorageTest',1);localStorage.removeItem('localStorageTest')}catch(e){return}
if(window.$isMobile){return}
var el=$('#rec'+recid).find('.t724__opener');var name=el.attr('data-cookie-name');var time=el.attr('data-cookie-time')*24*60*60*1000;var html=document.documentElement;var lstorage=sessionStorage.getItem(name);$('html').on('mouseleave',function(e){if(e.clientY>10){return}
var curDate=Math.floor(Date.now());if(time==0){lstorage=sessionStorage.getItem(name)}else{lstorage=localStorage.getItem(name)}
if(((lstorage==null||typeof lstorage=='undefined')&&!el.hasClass('t724__opener_activated'))||(lstorage<(curDate-time)&&time>0)){el.trigger('click');el.addClass('t724__opener_activated');if(time==0){sessionStorage.setItem(name,curDate)}
if(time>0){localStorage.setItem(name,curDate)}}})}
function t744_init(recid){t_sldsInit(recid);setTimeout(function(){t_prod__init(recid)},500);$('#rec'+recid).find('.t744').bind('displayChanged',function(){t744_updateSlider(recid)})}
function t744_updateSlider(recid){var el=$('#rec'+recid);t_slds_SliderWidth(recid);sliderWrapper=el.find('.t-slds__items-wrapper');sliderWidth=el.find('.t-slds__container').width();pos=parseFloat(sliderWrapper.attr('data-slider-pos'));sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'});t_slds_UpdateSliderHeight(recid);t_slds_UpdateSliderArrowsHeight(recid)}
function t750_init(recid){t_sldsInit(recid);setTimeout(function(){t_prod__init(recid);t750_initPopup(recid)},500)}
function t750_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t-popup'),hook=el.attr('data-tooltip-hook'),analitics=el.attr('data-track-popup');if(hook!==''){var obj=$('a[href="'+hook+'"]');obj.click(function(e){t750_showPopup(recid);e.preventDefault();if(window.lazy=='y'){t_lazyload_update()}
if(analitics>''){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}})}}
function t750_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t-popup'),sliderWrapper=el.find('.t-slds__items-wrapper'),sliderWidth=el.find('.t-slds__container').width(),pos=parseFloat(sliderWrapper.attr('data-slider-pos'));popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show');t_slds_SliderWidth(recid);sliderWrapper=el.find('.t-slds__items-wrapper');sliderWidth=el.find('.t-slds__container').width();pos=parseFloat(sliderWrapper.attr('data-slider-pos'));sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'});t_slds_UpdateSliderHeight(recid);t_slds_UpdateSliderArrowsHeight(recid);if(window.lazy=='y'){t_lazyload_update()}},50);$('body').addClass('t-body_popupshowed');el.find('.t-popup').click(function(e){if(e.target==this){t750_closePopup()}});el.find('.t-popup__close, .t750__close-text').click(function(e){t750_closePopup()});$(document).keydown(function(e){if(e.keyCode==27){t750_closePopup()}})}
function t750_closePopup(){$('body').removeClass('t-body_popupshowed');$('.t-popup').removeClass('t-popup_show');setTimeout(function(){$('.t-popup').not('.t-popup_show').css('display','none')},300)}
function t750_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}
function t762_init(recid){t_sldsInit(recid);setTimeout(function(){t_prod__init(recid)},500);$('#rec'+recid).find('.t762').bind('displayChanged',function(){t_slds_updateSlider(recid)})}
function t764_updateSlider(recid){var el=$('#rec'+recid);t_slds_SliderWidth(recid);sliderWrapper=el.find('.t-slds__items-wrapper');sliderWidth=el.find('.t-slds__container').width();pos=parseFloat(sliderWrapper.attr('data-slider-pos'));sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'});t_slds_UpdateSliderHeight(recid);t_slds_UpdateSliderArrowsHeight(recid)}
function t770_init(recid){var rec=$('#rec'+recid);var navElem=rec.find('.t770');var isFixed=(navElem.css('position')=='fixed');var redactorMode=navElem.hasClass('t770_redactor-mode');if(!redactorMode){t770_highlight();navElem.removeClass('t770__beforeready');if(isFixed){t770_checkAnchorLinks(recid)}
if(isFixed&&navElem.attr('data-bgopacity-two')){t770_changebgopacitymenu(recid);$(window).bind('scroll',t_throttle(function(){t770_changebgopacitymenu(recid)},200))}
if(isFixed&&navElem.attr('data-appearoffset')){navElem.removeClass('t770__beforeready');t770_appearMenu(recid);$(window).bind('scroll',t_throttle(function(){t770_appearMenu(recid)},200))}}
if(rec.find('.t770__imglogo').attr('data-img-width')){t770_setLogoPadding(recid)}
if(rec.find('.t770__mobile_burger').length){t770_createMobileMenu(recid)}
t770_setBg(recid);$(window).bind('resize',t_throttle(function(){t770_setBg(recid)},200))}
function t770_setLogoPadding(recid){if($(window).width()>980){var t770__menu=$('#rec'+recid+' .t770');var t770__logo=t770__menu.find('.t770__logowrapper');var t770__leftpart=t770__menu.find('.t770__leftwrapper');var t770__rightpart=t770__menu.find('.t770__rightwrapper');t770__leftpart.css("padding-right",t770__logo.width()/2+50);t770__rightpart.css("padding-left",t770__logo.width()/2+50)}}
function t770_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t770__list_item a[href='"+url+"']").addClass("t-active");$(".t770__list_item a[href='"+url+"/']").addClass("t-active");$(".t770__list_item a[href='"+pathname+"']").addClass("t-active");$(".t770__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t770__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t770__list_item a[href='http://tilda.ws/%22+pathname+%22/']").addClass("t-active")}
function t770_checkAnchorLinks(recid){if($(window).width()>=960){var t770_navLinks=$("#rec"+recid+" .t770__desktoplist .t770__list_item a:not(.tooltipstered)[href*='#']");if(t770_navLinks.length>0){t770_catchScroll(t770_navLinks)}}}
function t770_catchScroll(t770_navLinks){var t770_clickedSectionId=null,t770_sections=new Array(),t770_sectionIdTonavigationLink=[],t770_interval=100,t770_lastCall,t770_timeoutId;t770_navLinks=$(t770_navLinks.get().reverse());t770_navLinks.each(function(){var t770_cursection=t770_getSectionByHref($(this));if(typeof t770_cursection.attr("id")!="undefined"){t770_sections.push(t770_cursection)}
t770_sectionIdTonavigationLink[t770_cursection.attr("id")]=$(this)});t770_updateSectionsOffsets(t770_sections);t770_sections.sort(function(a,b){return b.attr("data-offset-top")-a.attr("data-offset-top")});$(window).bind('resize',t_throttle(function(){t770_updateSectionsOffsets(t770_sections)},200));$('.t770').bind('displayChanged',function(){t770_updateSectionsOffsets(t770_sections)});setInterval(function(){t770_updateSectionsOffsets(t770_sections)},5000);t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId);t770_navLinks.click(function(){var t770_clickedSection=t770_getSectionByHref($(this));if(!$(this).hasClass("tooltipstered")&&typeof t770_clickedSection.attr("id")!="undefined"){t770_navLinks.removeClass('t-active');$(this).addClass('t-active');t770_clickedSectionId=t770_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t770_now=new Date().getTime();if(t770_lastCall&&t770_now<(t770_lastCall+t770_interval)){clearTimeout(t770_timeoutId);t770_timeoutId=setTimeout(function(){t770_lastCall=t770_now;t770_clickedSectionId=t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId)},t770_interval-(t770_now-t770_lastCall))}else{t770_lastCall=t770_now;t770_clickedSectionId=t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId)}})}
function t770_updateSectionsOffsets(sections){$(sections).each(function(){var t770_curSection=$(this);t770_curSection.attr("data-offset-top",t770_curSection.offset().top)})}
function t770_getSectionByHref(curlink){var t770_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(t770_curLinkValue[0]=='/'){t770_curLinkValue=t770_curLinkValue.substring(1)}
if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t770_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t770_curLinkValue.substring(1)+"']")}}
function t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId){var t770_scrollPosition=$(window).scrollTop(),t770_valueToReturn=t770_clickedSectionId;if(t770_sections.length!=0&&t770_clickedSectionId==null&&t770_sections[t770_sections.length-1].attr("data-offset-top")>(t770_scrollPosition+300)){t770_navLinks.removeClass('t-active');return null}
$(t770_sections).each(function(e){var t770_curSection=$(this),t770_sectionTop=t770_curSection.attr("data-offset-top"),t770_id=t770_curSection.attr('id'),t770_navLink=t770_sectionIdTonavigationLink[t770_id];if(((t770_scrollPosition+300)>=t770_sectionTop)||(t770_sections[0].attr("id")==t770_id&&t770_scrollPosition>=$(document).height()-$(window).height())){if(t770_clickedSectionId==null&&!t770_navLink.hasClass('t-active')){t770_navLinks.removeClass('t-active');t770_navLink.addClass('t-active');t770_valueToReturn=null}else{if(t770_clickedSectionId!=null&&t770_id==t770_clickedSectionId){t770_valueToReturn=null}}
return!1}});return t770_valueToReturn}
function t770_setPath(){}
function t770_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t770").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t770").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t770_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t770").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t770_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t770").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t770_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t770"),burger=el.find(".t770__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t770_opened")})
$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t776__init(recid){setTimeout(function(){t_prod__init(recid);t776_initPopup(recid);t776__updateLazyLoad(recid)},500)}
function t776__updateLazyLoad(recid){var scrollContainer=$("#rec"+recid+" .t776__container_mobile-flex");var curMode=$(".t-records").attr("data-tilda-mode");if(scrollContainer.length&&curMode!="edit"&&curMode!="preview"){scrollContainer.bind('scroll',t_throttle(function(){t_lazyload_update()},500))}}
function t776_initPopup(recid){var rec=$('#rec'+recid);rec.find('[href^="#prodpopup"]').one("click",function(e){e.preventDefault();var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');t_sldsInit(recid+' #t776__product-'+lid_prod+'')});rec.find('[href^="#prodpopup"]').click(function(e){e.preventDefault();t776_showPopup(recid);var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');el_popup.find('.js-product').css('display','none');var el_fullprod=el_popup.find('.js-product[data-product-lid="'+lid_prod+'"]')
el_fullprod.css('display','block');var analitics=el_popup.attr('data-track-popup');if(analitics>''){var virtTitle=el_fullprod.find('.js-product-name').text();if(!virtTitle){virtTitle='prod'+lid_prod}
Tilda.sendEventToStatistics(analitics,virtTitle)}
var curUrl=window.location.href;if(curUrl.indexOf('#!/tproduct/')<0&&curUrl.indexOf('%23!/tproduct/')<0){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tproduct/'+recid+'-'+lid_prod)}}
t776_updateSlider(recid+' #t776__product-'+lid_prod+'');if(window.lazy=='y'){t_lazyload_update()}});if($('#record'+recid).length==0){t776_checkUrl(recid)}
t776_copyTypography(recid)}
function t776_checkUrl(recid){var curUrl=window.location.href;var tprodIndex=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&tprodIndex<0){tprodIndex=curUrl.indexOf('%23!/tproduct/')}
if(tprodIndex>=0){var curUrl=curUrl.substring(tprodIndex,curUrl.length);var curProdLid=curUrl.substring(curUrl.indexOf('-')+1,curUrl.length);var rec=$('#rec'+recid);if(curUrl.indexOf(recid)>=0&&rec.find('[data-product-lid='+curProdLid+']').length){rec.find('[data-product-lid='+curProdLid+'] [href^="#prodpopup"]').triggerHandler('click')}}}
function t776_updateSlider(recid){var el=$('#rec'+recid);t_slds_SliderWidth(recid);var sliderWrapper=el.find('.t-slds__items-wrapper');var sliderWidth=el.find('.t-slds__container').width();var pos=parseFloat(sliderWrapper.attr('data-slider-pos'));sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'});t_slds_UpdateSliderHeight(recid);t_slds_UpdateSliderArrowsHeight(recid)}
function t776_showPopup(recid){var el=$('#rec'+recid);var popup=el.find('.t-popup');popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show');if(window.lazy=='y'){t_lazyload_update()}},50);$('body').addClass('t-body_popupshowed');el.find('.t-popup').click(function(e){if(e.target==this){t776_closePopup()}});el.find('.t-popup__close, .t776__close-text').click(function(e){t776_closePopup()});$(document).keydown(function(e){if(e.keyCode==27){t776_closePopup()}})}
function t776_closePopup(){$('body').removeClass('t-body_popupshowed');$('.t-popup').removeClass('t-popup_show');var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=curUrl.indexOf('%23!/tproduct/')}
curUrl=curUrl.substring(0,indexToRemove);setTimeout(function(){$(".t-popup").scrollTop(0);$('.t-popup').not('.t-popup_show').css('display','none');if(typeof history.replaceState!='undefined'){window.history.replaceState('','',curUrl)}},300)}
function t776_removeSizeStyles(styleStr){if(typeof styleStr!="undefined"&&(styleStr.indexOf('font-size')>=0||styleStr.indexOf('padding-top')>=0||styleStr.indexOf('padding-bottom')>=0)){var styleStrSplitted=styleStr.split(';');styleStr="";for(var i=0;i<styleStrSplitted.length;i++){if(styleStrSplitted[i].indexOf('font-size')>=0||styleStrSplitted[i].indexOf('padding-top')>=0||styleStrSplitted[i].indexOf('padding-bottom')>=0){styleStrSplitted.splice(i,1);i--;continue}
if(styleStrSplitted[i]==""){continue}
styleStr+=styleStrSplitted[i]+";"}}
return styleStr}
function t776_copyTypography(recid){var rec=$('#rec'+recid);var titleStyle=rec.find('.t776__title').attr('style');var descrStyle=rec.find('.t776__descr').attr('style');rec.find('.t-popup .t776__title').attr("style",t776_removeSizeStyles(titleStyle));rec.find('.t-popup .t776__descr, .t-popup .t776__text').attr("style",t776_removeSizeStyles(descrStyle))}
function t788_init(recid){setTimeout(function(){$('#rec'+recid+' .t788').addClass('js-product');$('#rec'+recid+' .t-cover__carrier').addClass('js-product-img');t_prod__init(recid)},500)}
function t803_init(recid){var el=$("#rec"+recid);var data=el.find('.t803__multi-datablock').children();var multidata={};$.each(data,function(){var source=$(this).children('.t803__multi-source').html();var value=$(this).children('.t803__multi-key-values').html();var key=$(this).children('.t803__multi-key').html();var def=$(this).children('.t803__multi-default').html();var v={};v[source]=value
multidata[source]={'default':def,'key':key,'values':v}});$.each($('[field]'),function(){fix=$(this).html().replace(/(?!%%)[A-zА-яё0-9_-]*(?=%%)/ig,'<span data-replace-key="$&"></span>');fix=fix.replace(/%{2}/igm,'');$(this).html(fix)});var params=window.location.search.replace('?','').split('&').reduce(function(p,e){var a=e.split('=');p[decodeURIComponent(a[0])+'='+decodeURIComponent(a[1])]=decodeURIComponent(a[0])+'='+decodeURIComponent(a[1]);return p},{});var stop=0;$.each(multidata,function(index,value){var key=params[index];if(typeof key!='undefined'){$('[data-replace-key='+value.key+']').html(value.values[key]);stop=1;console.log(value.values[key])}
if(stop===0){console.log(stop);$('[data-replace-key='+value.key+']').html(value.default)}})}
function t813_init(recid,height){t813__setHeight(recid,height);var doResize;$(window).resize(function(){clearTimeout(doResize);doResize=setTimeout(function(){t813__setHeight(recid)},200)})}
function t813__setHeight(recid,height){if(height==""||typeof height=="undefined"){var el=$("#rec"+recid),div=el.find(".t813__contentwrapper"),height=div.width()*0.5625;div.height(height);div.parent().height(height)}}
function t813_onSuccess(form){var inputsWrapper=form.find('.t-form__inputsbox');var inputsHeight=inputsWrapper.height();var inputsOffset=inputsWrapper.offset().top;var inputsBottom=inputsHeight+inputsOffset;var targetOffset=form.find('.t-form__successbox').offset().top;if($(window).width()>960){var target=targetOffset-200}else{var target=targetOffset-100}
if(targetOffset>$(window).scrollTop()||($(document).height()-inputsBottom)<($(window).height()-100)){inputsWrapper.addClass('t813__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:target},400);setTimeout(function(){inputsWrapper.addClass('t813__inputsbox_hidden')},400)}
var successurl=form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}